# -*- coding: utf-8 -*-
"""C2 Filtro Pasa Alto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RhnaHwWIqiQStLZ7oYsGSI00rIsfbIIz
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st

C2 = 291.73
C2min = C2*0.9
C2max = C2*1.1

x = np.random.uniform(C2min, C2max, 100) # Genero la dist. uniforme de valores de resistencias
media = np.mean(x)  # Calculo la media
sigma = np.std(x) # Calculo el desvío

normal = st.norm(media, sigma)  # Genero una distribución normal con la media y la varianza calculadas

print(sigma)
print(media)

x.sort()  # Ordeno el arreglo de valores aleatorios de R

Y = normal.pdf(x) # Genero un arreglo donde calculo la pdf para cada valor de R


# Gráficos
plt.plot(x,Y)
plt.grid()
plt.title("Distribución normal de C2 Pasa Alto")
plt.xlabel("[nF]")
plt.show()

np.mean(x)