# -*- coding: utf-8 -*-
"""Capacitores Filtro Pasa Bajo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XzqN4obgP18nm8IzKJT3yN1s-5fJreQx
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st

C = 174
Cmin = C*0.9
Cmax = C*1.1

x = np.random.uniform(Cmin, Cmax, 100) # Genero la dist. uniforme de valores de resistencias
media = np.mean(x)  # Calculo la media
sigma = np.std(x) # Calculo el desvío

normal = st.norm(media, sigma)  # Genero una distribución normal con la media y la varianza calculadas

print(sigma)
print(media)

x.sort()  # Ordeno el arreglo de valores aleatorios de R

Y = normal.pdf(x) # Genero un arreglo donde calculo la pdf para cada valor de R


# Gráficos
plt.plot(x,Y)
plt.grid()
plt.title("Distribución normal de C Pasa Bajo")
plt.xlabel("[nF]")
plt.show()

np.mean(x)