# -*- coding: utf-8 -*-
"""Resistencias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lo-L3YD-nSyaxx4R3PZwEUsVpDD4V3Fd
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st

R = 1000
Rmin = R*0.9
Rmax = R*1.1

x = np.random.uniform(Rmin, Rmax, 100) # Genero la dist. uniforme de valores de resistencias
media = np.mean(x)  # Calculo la media
sigma = np.std(x) # Calculo el desvío

normal = st.norm(media, sigma)  # Genero una distribución normal con la media y la varianza calculadas

print(sigma)
print(media)

x.sort()  # Ordeno el arreglo de valores aleatorios de R

Y = normal.pdf(x) # Genero un arreglo donde calculo la pdf para cada valor de R


# Gráficos
plt.plot(x,Y)
plt.grid()
plt.title("Distribución normal de R") 
plt.xlabel("[Ω]")
plt.show()