# -*- coding: utf-8 -*-
"""Wp1 Filtro Pasa Bajo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i3QaIXAIzifpYOt0eN900D5HH5w4s67F
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st

Wp1 = 8143.75
Wp1min = Wp1*0.9
Wp1max = Wp1*1.1

x = np.random.uniform(Wp1min, Wp1max, 100) # Genero la dist. uniforme de valores de resistencias
media = np.mean(x)  # Calculo la media
sigma = np.std(x) # Calculo el desvío

normal = st.norm(media, sigma)  # Genero una distribución normal con la media y la varianza calculadas

print(sigma)
print(media)

x.sort()  # Ordeno el arreglo de valores aleatorios de R

Y = normal.pdf(x) # Genero un arreglo donde calculo la pdf para cada valor de R


# Gráficos
plt.plot(x,Y)
plt.grid()
plt.title("Distribución normal de Wp1 Pasa Bajo")
plt.xlabel("[rad/s]")
plt.show()

np.mean(x)