# -*- coding: utf-8 -*-
"""Wp2 Filtro Pasa Alto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m1q5gekwZ4gBdo55R6CB6Kqix0BwllrQ
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st

Wp2 = 4847.68
Wp2min = Wp2*0.9
Wp2max = Wp2*1.1

x = np.random.uniform(Wp2min, Wp2max, 100) # Genero la dist. uniforme de valores de resistencias
media = np.mean(x)  # Calculo la media
sigma = np.std(x) # Calculo el desvío

normal = st.norm(media, sigma)  # Genero una distribución normal con la media y la varianza calculadas

print(sigma)
print(media)

x.sort()  # Ordeno el arreglo de valores aleatorios de R

Y = normal.pdf(x) # Genero un arreglo donde calculo la pdf para cada valor de R


# Gráficos
plt.plot(x,Y)
plt.grid()
plt.title("Distribución normal de Wp2 Pasa Alto")
plt.xlabel("[rad/s]")
plt.show()

np.mean(x)