# -*- coding: utf-8 -*-
"""Wp2Qp2 Pasa Alto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B582-BN9dz3x0heF8Q0ep8lLEwTgE34I
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st

Wp2Qp2 = 1896
Wp2Qp2min = Wp2Qp2*0.9
Wp2Qp2max = Wp2Qp2*1.1

x = np.random.uniform(Wp2Qp2min, Wp2Qp2max, 100) # Genero la dist. uniforme de valores de resistencias
media = np.mean(x)  # Calculo la media
sigma = np.std(x) # Calculo el desvío

normal = st.norm(media, sigma)  # Genero una distribución normal con la media y la varianza calculadas

print(sigma)
print(media)

x.sort()  # Ordeno el arreglo de valores aleatorios de R

Y = normal.pdf(x) # Genero un arreglo donde calculo la pdf para cada valor de R


# Gráficos
plt.plot(x,Y)
plt.grid()
plt.title("Distribución normal de Wp2/Qp2 Pasa Alto")
# plt.xlabel("[]")
plt.show()

np.mean(x)