# -*- coding: utf-8 -*-
"""WpQp Pasa Bajo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KgfpZz0vz3sLYbuyxdCgQsuA61yvCA0c
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st

WpQp = 3184
WpQpmin = WpQp*0.9
WpQpmax = WpQp*1.1

x = np.random.uniform(WpQpmin, WpQpmax, 100) # Genero la dist. uniforme de valores de resistencias
media = np.mean(x)  # Calculo la media
sigma = np.std(x) # Calculo el desvío

normal = st.norm(media, sigma)  # Genero una distribución normal con la media y la varianza calculadas

print(sigma)
print(media)

x.sort()  # Ordeno el arreglo de valores aleatorios de R

Y = normal.pdf(x) # Genero un arreglo donde calculo la pdf para cada valor de R


# Gráficos
plt.plot(x,Y)
plt.grid()
plt.title("Distribución normal de Wp/Qp Pasa Bajo")
# plt.xlabel("[]")
plt.show()

np.mean(x)